name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install mdbook
      run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        
    - name: Build
      run: bash publish.sh
